### ISSUE TITLE
Metadata: Add `package.xml` file to top of directory so testers can install via the FC Addon Manager and subsequently follow development easier

### ISSUE THREAD

**Issue by luzpaz** [wassimj/TopologicFC#1]
Reference: https://wiki.freecad.org/Package_Metadata

BTW, we need to know 3rd party software prerequisites.

Here's a template:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<package format="1" xmlns="https://wiki.freecad.org/Package_Metadata">
  <name>TopologicFC Workbench</name>
  <description>A Topologic Workbench for FreeCAD.</description>
  <version>0.1</version>
  <date>2022-XX-XX</date>
  <maintainer email="your_address@null.com">Your Name</maintainer>
  <license file="LICENSE">GPLv3.0</license>
  <url type="repository" branch="main">https://github.com/wassimj/TopologicFC</url>
  <icon>Resources/icons/TopologicWorkbench.svg</icon> <!-- If you include your icon here, you don't have to submit it to the main FreeCAD repo -->

  <content>
    <workbench>
      <classname>MyLegacyWorkbench</classname>
      <subdirectory>./</subdirectory>
      <depend></depend>
      <tag></tag>
      <tag></tag>
      <tag></tag>
    </workbench>
  </content>

</package>
````

**Comment by wassimj** [comment]
Done. Can you check please if it is correct and in the correct location? Thank you.

**Comment by wassimj** [comment]
So far there are no 3rd party software pre-requisites. Once I port more nodes, there will be 'soft' pre-requisites for 3rd party python libraries (e.g. openstudio, numpy, scipy, torch, etc etc).

**Comment by luzpaz** [comment]
> Done. Can you check please if it is correct and in the correct location? Thank you.

See #2 



> So far there are no 3rd party software pre-requisites. Once I port more nodes, there will be 'soft' pre-requisites for 3rd party python libraries (e.g. openstudio, numpy, scipy, torch, etc etc).

Once you do then you would make a `<depend>` tag for each pip installable python library. Then request for any to be added to https://github.com/FreeCAD/FreeCAD-addons/blob/master/ALLOWED_PYTHON_PACKAGES.txt if they aren't already.

**Comment by wassimj** [comment]
Thank you.
